import sublime, sublime_plugin, re;

class SetBufferNameCommand(sublime_plugin.WindowCommand):
	def run(self):
		view = self.window.active_view();

		settings = sublime.load_settings("SetBufferName.sublime-settings");
		self.bauto = settings.get("auto_prefix", False);
		self.prefix = settings.get("prefix", "-- [%s] %c");
		self.substitutions = settings.get("substitutions");

		if view.file_name() != None:
			sublime.status_message("Not a temporary buffer, cannot change name.");
			return False;

		# Authored by Dr. WritesCodeInAwfulBlocks (TODO: less awful)
		self.oldname = view.name();
		bnameisgenerated = view.substr(view.line(0))[0:len(self.oldname)] == self.oldname;

		prefixformatted = self.prefix.replace("%s", self.get_syntax(view));
		prefixcaretregex = re.search("%c", prefixformatted);
		prefixcaretpos = prefixcaretregex != None and prefixcaretregex.start() or -1;
		prefixformatted = prefixformatted.replace("%c", "");
		generatedtextstart = len(prefixformatted);
		if bnameisgenerated:
			prefixformatted += self.oldname;

		bnameempty = bnameisgenerated or view.name().strip() == "";
		# if the name of the buffer is the first line, then it was auto-generated by sublime; it should be replaced

		name = None;
		if bnameempty:
			name = prefixformatted;
		else:
			name = self.oldname;

		panel = self.window.show_input_panel("Set Name:", name, self.done, self.change, self.cancel);
		if bnameempty and prefixcaretregex > -1:
			panel.sel().clear(); # Clear the default caret placement
			if bnameisgenerated: # if the name is generated, select the inserted name, otherwise, use the caret specifier position
				panel.sel().add(sublime.Region(generatedtextstart, generatedtextstart + len(self.oldname)));
			else:
				panel.sel().add(sublime.Region(prefixcaretpos));


	def done(self, input):
		self.change_name(self.window.active_view(), input);

	def change(self, input):
		self.change_name(self.window.active_view(), input);

	def cancel(self):
		self.change_name(self.window.active_view(), self.oldname);
		
	def get_syntax(self, view):
		reg = re.search("/([^/]+).tmLanguage", view.settings().get("syntax"));
		if reg != None:
			syntax = reg.group(1);
			print(syntax.lower());
			print(self.substitutions);
			try:
				if syntax.lower() in self.substitutions:
					return self.substitutions[syntax.lower()];				
			except:
				pass;

			return syntax;

		return "ERROR RETRIEVING SYNTAX"; # Can a syntax file not actually exist?

	def change_name(self, view, name):
		view.set_name(name);
